apiVersion: v1
kind: Service
metadata:
 name: nodeapp
 
 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
 type: LoadBalancer
 selector:
  app: nodeapp
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80

    
    
 
