kind: Service
apiVersion: v1
metadata:
  name: nodeapp
spec:
  selector:
    app: nodeapp
  ports:
  - protocol: TCP
    port: 8291
    targetPort: 8101
    externalIp: 34.222.254.42
  type: LoadBalancer   
