kind: Service
apiVersion: v1
metadata:
  name: nodeapp
spec:
  type: NodePort
  selector:
    app: nodeapp
    
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30037
    targetPort: 80

    
    
 
